
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Clare
 */
public class creditsFrame extends javax.swing.JFrame {

    /**
     * Creates new form creditsFrame
     */
    public creditsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creditsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creditsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creditsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creditsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ;
            }
        });
    }

    public static void creditsFrame() { //This is the frame that contains the credits
        JFrame credits = new JFrame("Credits"); //Creates frame
        credits.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        basic g = new basic();  //Creates background
        //Default button and label dimensions
        int Dhori = 110;
        int Dvert = 30;
        int Lhori = 400;
        int Lvert = 50;
        
        JButton back = new JButton("Back"); //Creates button
        back.addActionListener(new ActionListener() {   //Adds action listener to button
            public void actionPerformed(ActionEvent e) {
                menuFrame.getMenu().setVisible(true);
                credits.dispose();
            }
        });
        
        //Creates labels
        JLabel title = new JLabel("Credits");
        JLabel cn = new JLabel("Corey Nambu, Cgnambu");
        JLabel cd = new JLabel("Clarence Domond, Cdomond");
        JLabel ms = new JLabel("Michael Surma, Masurma");
        JLabel jc = new JLabel("Joshua Cervantes, Jecervantes");
        
        //Sets fonts for labels
        title.setFont(new Font("Verdana", Font.BOLD, 18));
        cd.setFont(new Font("Verdana", Font.BOLD, 12));
        cn.setFont(new Font("Verdana", Font.BOLD, 12));
        ms.setFont(new Font("Verdana", Font.BOLD, 12));
        jc.setFont(new Font("Verdana", Font.BOLD, 12));
        
        //Set font colors
        title.setForeground(Color.BLACK);
        cn.setForeground(Color.BLACK);
        cd.setForeground(Color.BLACK);
        ms.setForeground(Color.BLACK);
        jc.setForeground(Color.BLACK);
        
        //Adds button and labels
        credits.add(back);
        credits.add(title);
        credits.add(cn);
        credits.add(cd);
        credits.add(ms);
        credits.add(jc);
        
        //Determinse the size and position of the button and labels
        back.setBounds(30, 350, Dhori, Dvert);
        title.setBounds(250, 10, Dhori, Dvert);
        cn.setBounds(200, 100, Lhori, Lvert);
        cd.setBounds(200, 150, Lhori, Lvert);
        ms.setBounds(200, 200, Lhori, Lvert);
        jc.setBounds(200, 250, Lhori, Lvert);
        
        //Draws background on frame and makes it visible
        credits.add(g);
        credits.pack();
        credits.setVisible(true);
        credits.setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
