
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Clare
 */
public class gameOverFrame extends javax.swing.JFrame {

    /**
     * Creates new form gameOverFrame
     */
    public gameOverFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ;
            }
        });
    }
    
    public static void gameOverFrame(int score) {    //This is the frame that displays at the end of the game
        JFrame gameOver = new JFrame("Game Over");  //Creates frame
        gameOver.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        basic g = new basic();  //Creates background
        //Default buttons size
        int Dhori = 110;
        int Dvert = 30;
        
        JButton retry = new JButton("Retry");   //Creates button
        retry.addActionListener(new ActionListener() {  //Adds action listener to button
            public void actionPerformed(ActionEvent e) {
                gameFrame.setChecksTrue();
                gameOver.dispose();
                menuFrame.getMenu().setVisible(true);
            }
        });
        
        JButton exit = new JButton("Exit"); //Creates button
        exit.addActionListener(new ActionListener() {   //Adds action listener to button
            public void actionPerformed(ActionEvent e) {
                gameOver.dispose();
                System.exit(0);
            }
        });
        
        //Creating labels
        JLabel title = new JLabel("GAME OVER");
        title.setFont(new Font("Verdana", Font.BOLD, 18));
        title.setForeground(Color.BLACK);
        JLabel displayScore = new JLabel("Score: " + score);
        displayScore.setFont(new Font("Verdana", Font.BOLD, 14));
        displayScore.setForeground(score > 60 ? Color.blue : Color.red);
        
        //Determines position and dimensions
        title.setBounds(240, 10, 200, 50);
        displayScore.setBounds(10, 50, 100, 50);
        gameOver.add(title);
        gameOver.add(displayScore);
        
        //Adds buttons to frame
        gameOver.add(retry);
        gameOver.add(exit);
        
        //Determines the size and position of the buttons
        retry.setBounds(450, 350, Dhori, Dvert);
        exit.setBounds(30, 350, Dhori, Dvert);
        
        //Draws background on frame and makes it visible
        gameOver.add(g);
        gameOver.pack();
        gameOver.setVisible(true);
        gameOver.setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
